config/routes.rb
Pinterest::Application.routes.draw do

  resources :pins

  devise_for :users
  root 'pages#index'
  
  get 'Home' => 'pages#index'

  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 before_filter :configure_permitted_parameters, if: :devise_controller?
 
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :phone) }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Pinterest</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
	<!-- Latest compiled and minified JavaScript -->
	<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
</head>
<body style="background-image: url(<%= image_path 'b.png' %>);">
	<%= render :partial => 'shared/header' %>
	<div><%= notice %></div>
	<div><%= alert %></div>
	<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron" style="background-image:url('http://www.onemonth.cl/assets/home-bg-15138263676a6f1ccde03ca52a29e2a0.jpg'); background-size:100%">
  <h1 title="first tooltip">Este es el Index h1</h1>
  <h2>Esto es un subtitulo h2</h2>
  <h3>Esto es un subtitulo h3</h3>
  <p><a class="btn btn-primary btn-lg" role="button" >Learn more</a></p>
  <p><a class="btn btn-primary btn-lg" data-placement="right" role="button">Learn more</a></p>
</div>

<script type="text/javascript">
	$('.btn').tooltip({title:"hola"});
</script>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="container">

<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>
</div>

app/views/pins/index.html.erb
<div class="container">

  <div class="row">

    <% @pins.each do |pin| %>

    <div class="col-xs-8 col-sm-1 col-md-3 col-lg-3">
      <div class="thumbnail" >
      <%= image_tag pin.photo, :class => "img-rounded" %>
        <div class="caption">
          <p>
            <%= pin.description %>
          </p>
          <p>
            <%= link_to 'Show', pin, :class => "btn btn-primary" %>
            <%= link_to 'Edit', edit_pin_path(pin), :class => "btn btn-default" %>
            <%= link_to 'Destroy', pin, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
          </p>
        </div>
      </div>
    </div>

    <% end %>

  </div>


  <br>
  <%= link_to 'New Pin', new_pin_path %>
</div>

app/views/pins/new.html.erb
<div class="container">

<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>
</div>

app/views/pins/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag(@pin.photo, :size => "200x200") %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation" >
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" style="padding-top: 0px; padding-bottom: 0px;" href="#"><img height="50" width="130" src="http://business.pinterest.com/assets/img/brand/pinterest_logo_white.png"></a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><a href="/Home">Home</a></li>
				<% if current_user.nil? %>
					<li><%= link_to("Ingresar",new_user_session_path) %></li>
				<% else %>
					<li><%= link_to("Pins",pins_path) %></li>
					<li><%= link_to("Log Out",destroy_user_session_path, :method => :delete) %></li>
				<% end %>
			</ul>
		</div><!-- /.navbar-collapse -->
	</nav>